version: 2.1
executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:0.14.7
jobs:
  terraform-validate:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform validate & Format
          command: |
            cd
            terraform init --backend=false
            terraform validate
            terraform fmt --check
  terraform-plan-and-apply:
    executor: terraform-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            pwd
            cd
            terraform init
            terraform plan
      - run:
          name: Terraform Apply
          command: |
            cd
            terraform apply --auto-approve
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts
  terraform-destory:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Terraform Destroy
          command: |
            terraform init
            terraform destroy --auto-approve

workflows:
  build_and_deploy:
    jobs:
      - terraform-validate
      - terraform-plan-and-apply:
          requires:
           - terraform-validate
      - hold:
          type: approval
          requires:
            - terraform-plan-and-apply
      - terraform-destory:
          requires:
            - hold




